var quotes = 
[
    "« The only limit to our realization of tomorrow will be our doubts of today. » Franklin D.Roosevelt.",
    "« There is nothing more profound in human existence than self-esteem. » Sándor Márai.",
    "« Life isn't about finding yourself. Life is about creating yourself. » George Bernard Shaw.",
    "« It is better to aim for perfection and miss than to aim for imperfection and hit. »",
    "« Only those who are crazy enough to think they can change the world can do it. » Steve Jobs.",
    "« Do not be afraid to be criticized; it's proof that you are becoming someone. »",
    "« If you want something you've never had, you must be willing to do something you've never done. »",
    "« Life flourishes through work. »",
    "« Victory over oneself is the greatest victory. »",
    "« Falling is allowed; getting up is mandatory. » Marcus Aurelius",
    "« Do not be discouraged; it is often the last key in the bunch that opens the door. »",
    "« Whatever you dream of doing, start it. »",
    "« The best way to predict the future is to create it. »",
    "« Be the change you wish to see in the world. »",
    "« A being who loves life lives first for the joy of being alive. » Jacques Ntéka Bokolo",
    "« Success is the best revenge. »",
    "« The optimist sees the problems and believes in the remedies. »",
    "« Courage is not the absence of fear, but the ability to overcome what scares you. » Nelson Mandela",
    "« What matters is not where you come from, but where you are going. »",
    "« Failure is not the opposite of success; it is part of success. »",
    "« The supreme irony of life is that no one gets out alive. »",
    "« Winning is not about finishing first. It's not about beating others. It's about conquering yourself. »",
    "« Only those who risk going too far will discover how far we can go. » Thomas Stearns Eliot",
    "« Demand a lot from yourself and expect little from others. You will avoid many troubles. »",
    "« When you are loved, you doubt nothing. When you love, you doubt everything. »",
    "« The only way to start is to stop talking and start acting. »",
    "« The stars will never align, and the traffic lights of life will never all turn green at the same time. The universe doesn't conspire against you, but it doesn't go out of its way to make things easy either. Conditions are never perfect. ‘Someday’ is a disease that will take your dreams to the grave with you. Pro and con lists are just as bad. If it's important to you and you want to do it ‘eventually’, just do it and correct course along the way. » Tim Ferriss",
    "« Succeed so high that you forget the people who didn't believe in you. » Yomi Denzel",
    "« Like a shooting star, human life on this Earth boils down to: Being born to be and appear, then disappear. » Taha-Hassine FERHAT",
    "« In 20 years, you will be more disappointed by the things you didn't do than by the ones you did. So break free from the beaten path. Set sail. Explore. Dream. Discover. » Napoleon Hill",
    "« Avoiding failure is avoiding progress. »",
    "« To love is to risk rejection. To live is to risk dying. To hope is to risk despair. To try is to risk failure. Risking is necessary. Only those who dare to risk are truly free. »",
    "« There are those who see things as they are and ask why. I dream of things that never were and ask why not. » Marc Lévy",
    "« It is nothing to die; it is terrible not to live. » Victor Hugo",
    "« Better to be alone than in bad company. »",
    "« Nothing in life is to be feared; it is only to be understood. Now is the time to understand more, so that we may fear less. » Marie Curie",
    "« You cannot forever escape what your heart desires. » Hélène Delanoy",
    "« Only remember the beautiful memories of the past. Live your present in harmony with your heart. And wait for the future to come to you with wisdom. » Valérie Coeur",
    "« The past is what no longer exists. Living in the past is not living: it is being dead or perhaps wanting to die... »",
    "« Men will never stop dreaming. » Marshall D. Teach, One Piece",
    "« The beauty of the result is found in the efforts you put into achieving it. » Dali Dutilleul",
    "« If you are born poor, it's not your fault, but if you die poor, it is your fault. »",
    "« At 4 years old, I already knew I was going to be the boss. » Eiichiro Oda",
    "« Don't try to be good; try to be the best. » MrDreamax",
    "« Work as if your life depended on it. Why? Because it does. » MrDreamax",
    "« Work hard AND smart. »",
    "« When you entertain yourself, it's not you killing time, but time killing you. »",
    "« First, change your life, then second, change the world. » MrDreamax",
    "« When you understand that stagnation is the same as dying, then you have understood everything. If you stand still, the world moves forward, so you move backward. Don't wait, change now. » MrDreamax",
    "« Beauty is in the eye of the beholder. » Oscar Wilde",
    "« Make your life a dream and a dream a reality. » Antoine de Saint-Exupéry",
    "« Live as if you were to die tomorrow. Learn as if you were to live forever. » Gandhi",
    "« What counts in a man is not the color of his skin or the texture of his hair, but the texture and quality of his soul. » Martin Luther King",
    "« Two things are infinite: the Universe and human stupidity. But in regards to the Universe, I am not yet completely sure. » Albert Einstein",
    "« It is from the hell of the poor that the paradise of the rich is made. » Victor Hugo",
    "« There is nothing worse than those who don't want to hear. » Molière",
    "« It is up to you to decide what you want to believe in. » Edward D. Newgate, One Piece",
    "« Evil begets evil, and destruction only breeds hatred. In the end, we are all human beings; let's love each other. » Brook, One Piece",
    "« The act of never doubting, that's what gives strength. » Rayleigh, One Piece",
    "« Being different is the most beautiful thing in life; I take it as a compliment. It's what makes me unique! » Brook, One Piece",
    "« How can humanity thrive when it spills its own blood? » Dragon, One Piece",
    "« In life, it is not forbidden to cry, but it should never prevent you from moving forward. » Shanks, One Piece",
    "« Don't just think about everything you've lost; the past belongs to the past. Try to focus on what you have left; that's the most important thing. » Jimbei, One Piece",
    "« When do you think a man dies? When he is shot in the heart? When he contracts an incurable disease? When he eats a soup of poisonous mushrooms? No. He dies when he is forgotten. » Dr. Hiluluk, One Piece",
    "« It's not a question of possibility; it's just a question of will. » Monkey D. Luffy",
    "« Things don't always go the way we want. » Madara, Naruto",
    "« Your time is the light, and distractions are the black hole that catches it. » Eliott Exe",
];

const p_element = document.getElementById("random_quote");

function updateQuote() {
    var randomQuote = quotes[Math.floor(Math.random() * quotes.length)];
    p_element.innerHTML = randomQuote;
}

updateQuote();

setInterval(updateQuote, 10000);
